sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
  - npm install
script:
  - npm run lint
  - npm run check-types
  - npm run coverage
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
